/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BluLight;

import Entities.ResearchEntity;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan Botha
 */
public class ResearchCreatorForm extends javax.swing.JFrame {

    /**
     * Creates new form ResearchCreatorForm
     */
    public ResearchCreatorForm() {
        initComponents();
        setIconImage(new ImageIcon(LoginForm.class.getResource("/Images/Logo.png")).getImage());
        txaEntry.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry (0/32000)"));
        setLocation(Main.paneX -getWidth()/2, Main.paneY -getHeight()/2);
    }
    
    public void checkFields(){
            btnSave.setEnabled(txfTitle.getText().length() > 0 &&
                txfTitle.getText().length() <= 20 &&
                txfFormula.getText().length() <= 35 &&
                txaEntry.getText() != null &&
                !txaEntry.getText().equals("") &&
                txaEntry.getText().length() <= 32000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txfTitle = new javax.swing.JTextField();
        lblFormula = new javax.swing.JLabel();
        txfFormula = new javax.swing.JTextField();
        scrlPneEntry = new javax.swing.JScrollPane();
        txaEntry = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Research Entry Creator");
        setAlwaysOnTop(true);

        lblTitle.setText("Research title:");

        txfTitle.setToolTipText("Enter a title here [1 - 20 characters]");
        txfTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfTitleKeyReleased(evt);
            }
        });

        lblFormula.setText("Related formula: ");

        txfFormula.setToolTipText("Enter the formula that is related to this entry [0-35 characters]");
        txfFormula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfFormulaKeyReleased(evt);
            }
        });

        txaEntry.setColumns(20);
        txaEntry.setLineWrap(true);
        txaEntry.setRows(5);
        txaEntry.setWrapStyleWord(true);
        txaEntry.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry"));
        txaEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txaEntryKeyReleased(evt);
            }
        });
        scrlPneEntry.setViewportView(txaEntry);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlPneEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFormula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfFormula))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormula)
                    .addComponent(txfFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlPneEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfTitleKeyReleased
        checkFields();
    }//GEN-LAST:event_txfTitleKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Main.paneX = getX() +getWidth()/2;
        Main.paneY = getY() +getHeight()/2;
        new LauncherForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ResearchEntity r = new ResearchEntity(String.format("%-36s%24s", Main.curProfile.getId(), txfTitle.getText()),
        txaEntry.getText(), 0, 0);
        if (!txfFormula.getText().equals("") && txfFormula.getText() != null) {
            r.setRelatedformula(txfFormula.getText());
        }else{
            r.setRelatedformula(null);
        }
        Main.dbm.addResearchRecord(r);
        Main.dbm.voteResearch(r, (byte)5);
        new LauncherForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txaEntryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaEntryKeyReleased
        //updates char count
        txaEntry.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry ("+txaEntry.getText().length() + "/32000)"));
        checkFields();
    }//GEN-LAST:event_txaEntryKeyReleased

    private void txfFormulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfFormulaKeyReleased
        checkFields();
    }//GEN-LAST:event_txfFormulaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrlPneEntry;
    private javax.swing.JTextArea txaEntry;
    private javax.swing.JTextField txfFormula;
    private javax.swing.JTextField txfTitle;
    // End of variables declaration//GEN-END:variables
}
